// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Application.Entities.Entities
{
    public partial class PR_tbProductos_ListResult
    {
        public int prod_Id { get; set; }
        public string prod_Codigo { get; set; }
        public string prod_Nombre { get; set; }
        public decimal prod_Precio { get; set; }
        public string tipro_Nombre { get; set; }
        public string unime_Nombre { get; set; }
    }
}
