// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Application.Entities.Entities
{
    public partial class PR_tbProductos_InsertResult
    {
    }
}
