// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Entities.Entities
{
    public partial class tbProductos
    {
        public int prod_Id { get; set; }
        public string prod_Codigo { get; set; }
        public string prod_Nombre { get; set; }
        public decimal prod_Precio { get; set; }
        public int tipro_Id { get; set; }
        public int unime_Id { get; set; }
        public bool prod_EsEliminado { get; set; }
        public int prod_UsuarioCrea { get; set; }
        public DateTime prod_FechaCrea { get; set; }
        public int? prod_UsuarioModifica { get; set; }
        public DateTime? prod_FechaModifica { get; set; }
    }
}