// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Entities.Entities
{
    public partial class tbTipoProductos
    {
        public int tipro_Id { get; set; }
        public string tipro_Codigo { get; set; }
        public string tipro_Nombre { get; set; }
        public bool tipro_EsEliminado { get; set; }
        public int tipro_UsuarioCrea { get; set; }
        public DateTime tipro_FechaCrea { get; set; }
        public int? tipro_UsuarioModifica { get; set; }
        public DateTime? tipro_FechaModifica { get; set; }
    }
}