// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Application.Entities.Entities
{
    public partial class tbUnidadMedidas
    {
        public int unime_Id { get; set; }
        public string unime_Codigo { get; set; }
        public string unime_Nombre { get; set; }
        public bool unime_EsEliminado { get; set; }
        public int unime_UsuarioCrea { get; set; }
        public DateTime unime_FechaCrea { get; set; }
        public int? unime_UsuarioModifica { get; set; }
        public DateTime? unime_FechaModifica { get; set; }
    }
}